[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "node index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckTimeout = 300
terminationGracePeriodSeconds = 60

[nixpacks]
nodejs-version = "16" 